name: Generate Matrix
description: Generate Matrix
author: Argenis Ruben Dominguez
email: argenis.dominguez@hotmail.com

inputs:
  path:
    required: true
    description: Path to the test specs

outputs:
  matrix:
    description: Matrix of runners

  runners:
    description: Number of runners

runs:
  using: composite
  steps:
    - name: Set Matrix
      id: set-matrix
      shell: bash
      run: |
        RNERS=$(find "${{ inputs.path }}" -type f -name "*.ts" | wc -l | xargs)
        echo "matrix=[$(seq -s, 1 $RNERS)]" | sed 's/,$//' >> "$GITHUB_OUTPUT"
        echo "runners=$RNERS" >> "$GITHUB_OUTPUT"
