name: Generate Matrix
description: Generate Matrix
author: Argenis Ruben Dominguez
email: argenis.dominguez@hotmail.com

inputs:
  path:
    required: true
    description: Path to the test specs

outputs:
  matrix:
    description: Comma-separated list of numbers to use in a matrix
    value: ${{ steps.set-matrix.outputs.matrix }}

  runners:
    description: Total count of .ts files
    value: ${{ steps.set-matrix.outputs.runners }}

runs:
  using: composite
  shell: bash
  steps:
    - uses: actions/checkout@v4
    - name: Set Matrix
      id: set-matrix
      run: |
        chmod +x ./.github/actions/matrix/index.sh
        ./.github/actions/matrix/index.sh
