name: Selenium

on:
  push:
    branches: [main]

jobs:
  using-selenium:
    runs-on: ubuntu-latest
    container: selenium/node-chrome-112.0-chromedriver-112.0 

    steps:
      - name: Check version
        run: |
          chrome --version
          node --version
          npm --version
