name: Selenium

on:
  push:
    branches: [main]

jobs:
  using-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Installed versions
        run: |
          echo "Node   : $(node --version)"
          echo "NPM    : $(npm --version)"
          echo "Java   : $(java --version)"
          echo "Chrome : $(google-chrome --version)"
          
