name: Selenium

on:
  push:
    branches: [main]

jobs:
  using-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Check version
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Check versions
        run: |
          node --version
          npm --version
          
