name: Selenium

on:
  push:
    branches: [main]

jobs:
  using-selenium:
    runs-on: ubuntu-latest
    container: selenium/node-chrome

    steps:
      - name: Check version
        run: |
          node --version
          npm --version
          chrome --version
