name: WDIO

on:
  push:
    branches: [main]

jobs:
  using-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Check Installed versions
        run: |
          echo "Node   : $(node --version)"
          echo "NPM    : $(npm --version)"
          echo "Chrome : $(google-chrome --version)"
          echo "Java   : \n$(java --version)"

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          npm install
          npm install -g allure-commandline

      - name: Run WDIO Scripts
        run: npm run wdio

      - name: Generate Allure Report
        run: npx allure generate --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: allure-report
          
