name: WDIO

on:
  workflow_dispatch:

jobs:
  # send-notification-email:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Emailer Action
  #       uses: RubenDguez/emailer@v0.1.1-alpha
  #       with:
  #         secrets_user: ${{ secrets.EMAIL_USER }}
  #         secrets_pass: ${{ secrets.EMAIL_PASS }}
  #         from: 'GH-ACTIONS-TESTS donot.reply@github.com <${{ secrets.EMAIL_USER }}>'
  #         to: 'argenis.dominguez@hotmail.com'
  #         subject: 'WDIO Is About to start'
  #         html: '<h1>Hello there, the WDIO Workflow is about to start</h1>'

  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      runners: ${{ steps.set-matrix.outputs.runners }}

    steps:
      - uses: actions/checkout@v4
      - name: Set Matrix
        id: set-matrix
        uses: ./.github/actions/matrix/
        with:
          path: './test/specs'

  run-scripts:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.runner }}
      - name: Run WDIO Scripts
        uses: ./.github/actions/wdio
        with:
          current: ${{ matrix.runner }}
          of: ${{ needs.setup-matrix.outputs.runners }}
          run_id: ${{ github.run_id }}

  generate-report:
    needs: run-scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Report
        uses: ./.github/actions/allure/generate/

  send-report-link-email:
    needs: generate-report
    runs-on: ubuntu-latest

    steps:
      - name: Emailer Action
        uses: RubenDguez/emailer@v0.1.1-alpha
        with:
          secrets_user: ${{ secrets.EMAIL_USER }}
          secrets_pass: ${{ secrets.EMAIL_PASS }}
          from: 'GH-ACTIONS-TESTS donot.reply@github.com <${{ secrets.EMAIL_USER }}>'
          to: 'argenis.dominguez@hotmail.com'
          subject: 'WDIO just finished running'
          html: '
            <div>
              <h1>Hello there, the WDIO Workflow just finished running</h1>
              <p>Please follow this link in order to download the report <a href="www.google.com">click here.</a></p>
            </div>
            '
        