name: WDIO

on:
  push:
    branches: [main]

jobs:
  send-notification-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        run: |
          echo "Sending Email using node mailer"

  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runner: [1, 2, 3, 4, 5]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          npm install
          npm install -g allure-commandline

      - name: Run WDIO Scripts
        run: npm run wdio -- --shard=${{ matrix.runner }}/5

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: allure-results
          name: allure-results-${{ github.run_id }}-${{ matrix.runner }}

  generate-report:
    needs: run-scripts
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Generate Report
        run: |
          ls -la

      
          
